config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root 'home#index'

  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: '/dashboard'

    resources :payment_methods, only: %i[new create show destroy index], shallow: true do
      post 'enable', on: :member
      post 'disable', on: :member
    end
  end

  resources :companies, only: %i[index edit update show] do
    get '/payment_settings', to: 'companies#payment_settings'
    put '/cancel_registration', to: 'companies#cancel_registration'
    get 'pending', on: :collection
    post 'accept', on: :member

    resources :rejected_companies, only: %i[new create]
  end

  resources :purchases, only: %i[index] do
    post 'pending', on: :member

    resources :frauds, only: %i[show new create]
  end

  resources :frauds, only: %i[index]

  resources :pix_settings, only: %i[new create] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  resources :boleto_settings, only: %i[new create] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  resources :credit_card_settings, only: %i[new create] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :customers, only: %i[index show create]
      resources :pix_settings, only: %i[index show]
      resources :boleto_settings, only: %i[index show]
      resources :credit_card_settings, only: %i[index show]
      resources :customer_payment_methods, only: %i[index show create]
      resources :products, only: %i[index create show update] do
        post 'enable', on: :member
        post 'disable', on: :member
      end
      resources :purchases, only: %i[index create show update]
      resources :customer_subscriptions, only: %i[create index show]
      resources :receipts, only: %i[index show]
    end
  end

  resources :products, only: %i[new create show index] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  resources :subscriptions, only: %i[new create show] do
    post 'enable', on: :member
    post 'disable', on: :member
  end
end

app/views/payment_settings/_BoletoSetting.html.erb
<div id=<%= payment_setting.token %>>
    <p><%= BoletoSetting.human_attribute_name('bank_code') %>: <%= payment_setting.bank_code %></p>
    <p><%= BoletoSetting.human_attribute_name('agency_number') %>: <%= payment_setting.agency_number %></p>
    <p><%= BoletoSetting.human_attribute_name('account_number') %>: <%= payment_setting.account_number %></p>
    <p><%= BoletoSetting.human_attribute_name('status') %>: <%= BoletoSetting.human_attribute_name("status.#{payment_setting.status}") %></p>
    <div class="mx-5 lg:ml-20 my-auto">
    <% if payment_setting.enabled? %>
        <%= link_to t('common.disable'), disable_boleto_setting_path(payment_setting), method: :post, class: "bg-white hover:text-red-700 text-red-600 font-bold mb-2 py-2 px-4 border border-red-600 rounded focus:outline-none" %>
    <% else %>
        <%= link_to t('common.enable'), enable_boleto_setting_path(payment_setting), method: :post, class: "bg-white hover:text-green-700 text-green-600 font-bold mb-2 py-2 px-4 border border-green-600 rounded focus:outline-none" %>
    <% end %>
    </div>
</div>

app/views/payment_settings/_CreditCardSetting.html.erb
<div id=<%= payment_setting.token %>>
    <p><%= CreditCardSetting.human_attribute_name('company_code') %>: <%= payment_setting.company_code %></p>
    <p><%= CreditCardSetting.human_attribute_name('status') %>: <%= CreditCardSetting.human_attribute_name("status.#{payment_setting.status}") %></p>
    <div class="mx-5 lg:ml-20 my-auto">
    <% if payment_setting.enabled? %>
        <%= link_to t('common.disable'), disable_credit_card_setting_path(payment_setting), method: :post, class: "bg-white hover:text-red-700 text-red-600 font-bold mb-2 py-2 px-4 border border-red-600 rounded focus:outline-none" %>
    <% else %>
        <%= link_to t('common.enable'), enable_credit_card_setting_path(payment_setting), method: :post, class: "bg-white hover:text-green-700 text-green-600 font-bold mb-2 py-2 px-4 border border-green-600 rounded focus:outline-none" %>
    <% end %>
    </div>
</div>

app/views/payment_settings/_PixSetting.html.erb
<div id=<%= payment_setting.token %>>
    <p><%= PixSetting.human_attribute_name('pix_key') %>: <%= payment_setting.pix_key %></p>
    <p><%= PixSetting.human_attribute_name('bank_code') %>: <%= payment_setting.bank_code %></p>
    <p><%= PixSetting.human_attribute_name('status') %>: <%= PixSetting.human_attribute_name("status.#{payment_setting.status}") %></p>
    <div class="mx-5 lg:ml-20 my-auto">
    <% if payment_setting.enabled? %>
        <%= link_to t('common.disable'), disable_pix_setting_path(payment_setting), method: :post, class: "bg-white hover:text-red-700 text-red-600 font-bold mb-2 py-2 px-4 border border-red-600 rounded focus:outline-none" %>
    <% else %>
        <%= link_to t('common.enable'), enable_pix_setting_path(payment_setting), method: :post, class: "bg-white hover:text-green-700 text-green-600 font-bold mb-2 py-2 px-4 border border-green-600 rounded focus:outline-none" %>
    <% end %>
    </div>
</div>