config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root 'home#index'

  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: '/dashboard'

    resources :payment_methods, only: %i[new create show destroy index], shallow: true do
      post 'enable', on: :member
      post 'disable', on: :member
    end
  end

  resources :companies, only: %i[index edit update show] do
    get '/payment_settings', to: 'companies#payment_settings'
    put '/cancel_registration', to: 'companies#cancel_registration'
    get 'pending', on: :collection
    post 'accept', on: :member

    resources :rejected_companies, only: %i[new create]
  end

  resources :purchases, only: %i[index] do
    post 'pending', on: :member

    resources :frauds, only: %i[show new create]
  end

  resources :frauds, only: %i[index]

  resources :pix_settings, only: %i[new create] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  resources :boleto_settings, only: %i[new create] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  resources :credit_card_settings, only: %i[new create] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :customers, only: %i[index show create]
      resources :pix_settings, only: %i[index show]
      resources :boleto_settings, only: %i[index show]
      resources :credit_card_settings, only: %i[index show]
      resources :customer_payment_methods, only: %i[index show create]
      resources :products, only: %i[index create show update] do
        post 'enable', on: :member
        post 'disable', on: :member
      end
      resources :purchases, only: %i[index create show update]
      resources :customer_subscriptions, only: %i[create index show]
      resources :receipts, only: %i[index show]
    end
  end

  resources :products, only: %i[new create show index] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  resources :subscriptions, only: %i[new create show] do
    post 'enable', on: :member
    post 'disable', on: :member
  end
end

app/views/shared/_admin_navbar.html.erb
<nav class="bg-white border-b-2 border-purple-900">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between space-x-4 h-24 lg:h-16">
      <% if current_admin %>
        <div class="flex flex-wrap items-center space-x-2">
          <p class="text-pink-900 font-medium">Métodos de pagamento > </p>
          <%= link_to 'Criar novo', new_admin_payment_method_path, class: "bg-white hover:text-red-900 text-pink-900 font-medium py-1 px-4 border border-pink-900 rounded focus:outline-none" %>
          <%= link_to 'Listar todos', admin_payment_methods_path, class: "bg-white hover:text-red-900 text-pink-900 font-medium py-1 px-4 border border-pink-900 rounded focus:outline-none" %>
        <div class="text-pink-900 font-medium">Empresas > </div>
          <%= link_to 'Gerenciar Empresas', companies_path, class: "bg-white hover:text-red-900 text-pink-900 font-medium py-1 px-4 border border-pink-900 rounded focus:outline-none" %>
        <div class="text-pink-900 font-medium">Fraudes > </div>
          <%= link_to 'Fraudes Constatadas', frauds_path, class: "bg-white hover:text-red-900 text-pink-900 font-medium py-1 px-4 border border-pink-900 rounded focus:outline-none" %>
          <%= link_to 'Avaliar Fraudes', purchases_path, class: "bg-white hover:text-red-900 text-pink-900 font-medium py-1 px-4 border border-pink-900 rounded focus:outline-none" %>
      <% end %>    
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="bg-purple-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-2 lg:px-2">
  <div class="relative flex items-center justify-between h-16">
    <div class="flex title-font font-medium items-center text-gray-900 ml-10">
      <svg class="w-10 h-10 text-white p-2 bg-purple-500 rounded-full" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path>
      </svg>
      <span class="ml-3 text-xl text-white font-semibold" >PagaPaga</span>
    </div>

    <div>
      <% if current_user %>
      <div class="md:flex items-center mr-10">
        <%= link_to current_user.email, company_path(current_user.company.id), class: "text-white text-medium hover:underline"  %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "py-4 px-2 text-white font-medium hover:underline transition duration-300" %>
        </div>
      <% elsif current_admin %>
        <span class="text-white text-medium">
          <%= current_admin.email %>
        </span>
        <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: "py-4 px-2 text-white font-medium hover:underline transition duration-300 mr-10" %>
      <% else %>
        <div class="md:flex items-center mr-10">
          <%= link_to 'Cadastre-se', new_user_registration_path, class: "py-4 px-2 text-white font-medium hover:underline transition duration-300" %>
          <%= link_to 'Entrar', new_user_session_path, class: "py-4 px-2 text-white font-medium hover:underline transition duration-300" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_user_navbar.html.erb
<nav class="bg-white border-b-2 border-purple-900">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
  <div class="relative flex items-center justify-start space-x-4 h-16">
    <div class="text-pink-900 font-medium">Produtos e Assinaturas > </div>
      <%= link_to 'Criar produto', new_product_path, class: "bg-white hover:text-red-900 text-pink-900 font-medium py-1 px-4 border border-pink-900 rounded focus:outline-none" %>
      <%= link_to 'Listar produtos', products_path, class: "bg-white hover:text-red-900 text-pink-900 font-medium py-1 px-4 border border-pink-900 rounded focus:outline-none" %>
    <div>
  </div>
</nav>