config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root 'home#index'

  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: '/dashboard'

    resources :payment_methods, only: %i[new create show destroy index], shallow: true do
      post 'enable', on: :member
      post 'disable', on: :member
    end
  end

  resources :companies, only: %i[index edit update show] do
    get '/payment_settings', to: 'companies#payment_settings'
    put '/cancel_registration', to: 'companies#cancel_registration'
    get 'pending', on: :collection
    post 'accept', on: :member

    resources :rejected_companies, only: %i[new create]
  end

  resources :purchases, only: %i[index] do
    post 'pending', on: :member

    resources :frauds, only: %i[show new create]
  end

  resources :frauds, only: %i[index]

  resources :pix_settings, only: %i[new create] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  resources :boleto_settings, only: %i[new create] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  resources :credit_card_settings, only: %i[new create] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :customers, only: %i[index show create]
      resources :pix_settings, only: %i[index show]
      resources :boleto_settings, only: %i[index show]
      resources :credit_card_settings, only: %i[index show]
      resources :customer_payment_methods, only: %i[index show create]
      resources :products, only: %i[index create show update] do
        post 'enable', on: :member
        post 'disable', on: :member
      end
      resources :purchases, only: %i[index create show update]
      resources :customer_subscriptions, only: %i[create index show]
      resources :receipts, only: %i[index show]
    end
  end

  resources :products, only: %i[new create show index] do
    post 'enable', on: :member
    post 'disable', on: :member
  end

  resources :subscriptions, only: %i[new create show] do
    post 'enable', on: :member
    post 'disable', on: :member
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :pix_settings, dependent: :destroy
  has_many :credit_card_settings, dependent: :destroy
  has_many :boleto_settings, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :customers, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_one :rejected_company, dependent: :destroy

  enum status: { incomplete: 0, pending: 10, accepted: 20, rejected: 30 }

  has_one :owner, -> { where owner: true },
          class_name: 'User', inverse_of: 'company', dependent: :destroy

  after_save :check_if_still_incomplete
  after_save :generate_token_if_accepted

  validates :cnpj, :legal_name, :billing_address, :billing_email,
            presence: true, on: :update
  validates :billing_email, private_email: true, on: :update
  validates :cnpj, cnpj: true, on: :update

  def payment_settings
    pix_settings + credit_card_settings + boleto_settings
  end

  def blank_all_info!
    self.cnpj = ''
    self.legal_name = ''
    self.billing_address = ''
    self.billing_email = ''
    self.status = :incomplete

    save(validate: false)
  end

  private

  def any_essential_info_blank?
    [cnpj, legal_name, billing_address, billing_email].all?(&:blank?)
  end

  def check_if_still_incomplete
    pending! if !any_essential_info_blank? && incomplete?
  end

  def accepted_but_no_token?
    token.blank? && accepted?
  end

  def generate_token_if_accepted
    return unless accepted_but_no_token?

    self.token = generate_token
    save!
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_admin!, only: %i[index pending accept]
  before_action :authenticate_user!, except: %i[index pending accept]
  skip_before_action :redirect_empty_company_users, only: %i[edit update]
  before_action :find_company_and_authenticate_owner, only: %i[edit update cancel_registration]
  before_action :redirect_if_pending_company, only: %i[edit update]
  before_action :find_company, only: %i[show]
  before_action :authenticate_company_user, only: %i[show]
  before_action :authenticate_user_company_accepted, only: %i[payment_settings]

  def index
    @companies = Company.all
  end

  def show; end

  def edit; end

  def update
    if @company.update(edit_company_params)
      @company.pending! if @company.rejected?
      redirect_to @company, notice: t('.complete_success_notice')
    else
      render :edit
    end
  end

  def payment_settings
    @enabled_payment_methods = PaymentMethod.query_for_enabled
    @payment_settings = current_user.company.payment_settings
  end

  def cancel_registration
    @company.blank_all_info!

    redirect_to root_path
  end

  def pending
    @companies = Company.where(status: 'pending')
  end

  def accept
    @company = Company.find(params[:id])

    @company.accepted!
    redirect_to companies_path
  end

  private

  def edit_company_params
    params.require(:company).permit(
      :legal_name,
      :cnpj,
      :billing_email,
      :billing_address
    )
  end
end

app/views/companies/edit.html.erb
<h2>
  <% if @company.incomplete? %>
    <div class="block text-gray-700 text-sm font-bold ml-5 my-2">
      <%= t '.ask_to_complete_company' %>
    </div>
  <% elsif @company.accepted? %>
    <div class="block text-gray-700 text-sm font-bold ml-5 my-2">
      <%= t '.edit_company_message' %>
    </end>
  <% end %>
</h2>

<% if @company.errors.any? %>
  <ul>
    <% @company.errors.full_messages.each do |error| %>
      <li class="ml-5 mt-1 text-red-500"><%= error %></li>
    <% end %>
  </ul>
<% end %>
<div class="max-w-xs m-5 text-center rounded-lg shadow-md p-4 bg-white border">
  <%= form_for @company, :url => company_path(@company), method: :patch do |f| %>
    <div class="form-m-w-content">
      <div class="mb-4">
        <%= f.label :legal_name, class: "form-label" %>
        <%= f.text_field :legal_name, class: "form-text-field" %>
      </div>
      <div class="mb-4">
        <%= f.label :cnpj, class: "form-label" %>
        <%= f.text_field :cnpj, class: "form-text-field" %>
      </div>
      <div class="mb-4">
        <%= f.label :billing_address, class: "form-label" %>
        <%= f.text_field :billing_address, class: "form-text-field" %>
      </div>
      <div class="mb-4">
        <%= f.label :billing_email, class: "form-label" %>
        <%= f.text_field :billing_email, class: "form-text-field" %>
      </div>
      <%= f.submit t('common.submit'), class: "form-submit-button" %>
    </div>
  <% end %>
</div>

app/views/companies/index.html.erb
<div>
    <div class="w-auto">
        <table class="m-full ml-5 mt-5 text-center rounded-lg shadow-md p-4 bg-white border">
        <thead class="bg-gray-50 border-b">
            <tr>
                <th class="p-4 text-left text-gray-700 font-bold w-1/4">
                    Owner
                </th>
                <th class="p-4 text-left text-gray-700 font-bold w-1/4">
                    Empresa
                </th>
                <th class="p-4 text-left text-gray-700 font-bold w-1/4">
                    Status
                </th>
                <th class="p-4 text-left text-gray-700 font-bold">
                    Motivo de Rejeição
                </th>
            </tr>
            </thead
            <% @companies.each do |company| %>
              <tbody>
                <tr class="border-b">
                    <td class="p-4 text-justify">
                        <%= company.users.where(owner: true).first.email %>
                    </td>
                    <td class="p-4 text-justify">
                        <%= company.legal_name %>
                    </td>
                    <td class="p-4 text-justify">
                      <% if company.pending? %>
                        <span class="bg-yellow-100 text-yellow-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md"><%= Company.human_attribute_name("status.#{company.status}").capitalize %></span>
                      <% elsif company.accepted? %>
                        <span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md"><%= Company.human_attribute_name("status.#{company.status}").capitalize %></span>
                      <% elsif company.rejected?%>
                        <span class="bg-red-100 text-red-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md"><%= Company.human_attribute_name("status.#{company.status}").capitalize %></span> 
                      <% end %>
                    </td>
                    <td class="p-4 text-justify">
                        <% if company.status == 'rejected'%>
                            <%= company.rejected_company.reason %>
                        <% end %>
                    </td>
                </tr>
              </tbody>
            <% end %>
        </table>
    </div>
    <div class="mt-5">
        <%= link_to 'Empresas Pendentes', pending_companies_path, class: "m-5 text-purple-900 hover:underline"  %>
    </div>
</div>

app/views/companies/payment_settings.html.erb
<div>
    <% PaymentMethod.types.each do |payment_method_type| %>
        <div class="m-5">
        <%= 
        link_to "#{t('.new_payment_setting_prefix')} #{PaymentMethod.human_type_of_name(payment_method_type).downcase}", 
        "/#{payment_method_type}_settings/new",
        class: "text-purple-900 font-medium hover:underline" 
        %>
        </div>
    <% end %>
</div>

<div>
  <% @payment_settings.each do |ps| %>
    <%= render partial: "payment_settings/#{ps.class}", locals: { payment_setting: ps } %>
  <% end %>
</div>

app/views/companies/pending.html.erb
<h3 class="m-5">Empresas Pendentes</h3>
    
<div class="mr-10">
  <table class="w-full ml-5 mt-5 text-center rounded-lg shadow-md p-4 bg-white border">
    <thead class="bg-gray-50 border-b">    
      <tr>
        <th class="p-4 text-left text-gray-700 font-bold w-1/4">Owner</th>
        <th class="p-4 text-left text-gray-700 font-bold w-1/3">Empresa</th>
        <th class="p-4 text-left text-gray-700 font-bold w-1/4">Status</th>
        <th class="p-4 text-left text-gray-700 font-bold w-1/3">Ação</th>
      </tr>
    </thead>
      <% @companies.each do |company| %>
        <tbody>
          <tr>
            <td  class="p-4 text-justify">
              <%= company.users.where(owner: true).first.email %>
            </td>
            <td  class="p-4 text-justify">
              <%= company.legal_name %>
            </td>
            <td  class="p-4 text-justify">
              <% if company.pending? %>
                <span class="bg-yellow-100 text-yellow-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md"><%= Company.human_attribute_name("status.#{company.status}").capitalize %></span>
              <% elsif company.accepted? %>
                <span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md"><%= Company.human_attribute_name("status.#{company.status}").capitalize %></span>
              <% elsif company.rejected?%>
                <span class="bg-red-100 text-red-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md"><%= Company.human_attribute_name("status.#{company.status}").capitalize %></span> 
              <% end %>
            </td>
            <td  class="p-4 text-justify space-x-4">
              <%= link_to 'Aprovar', accept_company_path(company), method: :post, class: "bg-white hover:text-green-700 text-green-800 font-bold py-2 px-2 border border-green-800 rounded focus:outline-none"%>
              <%= link_to 'Rejeitar', new_company_rejected_company_path(company), class: "bg-white hover:text-red-700 text-red-800 font-bold py-2 px-2 border border-red-800 rounded focus:outline-none"%>
            </td>
          </tr>
        </tbody>
      <% end %>
  </table>
</div>

app/views/companies/show.html.erb
<p class="text-gray-800 font-medium ml-5 my-5 text-justify">
  <b><%= Company.human_attribute_name('status') %>: </b>
  <% if @company.pending? %>
    <span class="bg-yellow-100 text-yellow-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md">
      <%= Company.human_attribute_name("status.#{@company.status}") %>
    </span>
  <% elsif @company.accepted? %>
    <span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md">
    <%= Company.human_attribute_name("status.#{@company.status}") %>
    </span>
  <% elsif @company.rejected?%>
    <span class="bg-red-100 text-red-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md">
      <%= Company.human_attribute_name("status.#{@company.status}") %>
    </span> 
  <% end %>
</p>

<% if @company.accepted? %>
    <%= link_to t('.configure_payment'), company_payment_settings_path(@company), class: "ml-5 text-purple-900 font-medium hover:underline" %>
<% end %>

<div class="max-w-lg ml-5 mt-5 mb-7 rounded-lg shadow-md p-4 bg-white border">
  <ul>
    <li class="text-justify text-gray-700 text-sm font-bold ml-5 my-2"><%= Company.human_attribute_name('legal_name') %>:
    <span> <%= @company.legal_name %></span></li>
    <li class="text-justify text-gray-700 text-sm font-bold ml-5 my-2"><%= Company.human_attribute_name('cnpj') %>:
    <span> <%= @company.cnpj %></span></li>
    <li class="inline text-justify text-gray-700 text-sm font-bold ml-5 my-2"><%= Company.human_attribute_name('billing_email') %>:
    <span class="ml-10 sm:ml-1"><%= @company.billing_email %></span></li>
    <li class="text-justify text-gray-700 text-sm font-bold ml-5 my-2"><%= Company.human_attribute_name('billing_address') %>:
    <span><%= @company.billing_address %></span></li>
    <% if @company.token %>
      <p class="text-justify text-gray-700 text-sm font-bold ml-5 my-2"><%= t('.token_explanation') %></p>
      <li class="text-justify text-gray-700 text-sm font-bold ml-5 my-2"><%= Company.human_attribute_name('token') %>:
      <span><%= @company.token %></span></li>
    <% end %>
  </ul>
</div>

<% if current_user&.owns?(@company) %>
  <% if @company.pending? %>
    <%= link_to 'Cancelar pedido de registro', company_cancel_registration_path(@company, id: @company.id), method: :put, class: "bg-white hover:text-red-800 text-red-700 font-bold ml-5 mt-5  py-2 px-4 border border-red-700 rounded focus:outline-non" %>
  <% else %>
    <%= link_to 'Editar dados', edit_company_path(@company), class: "bg-white hover:text-purple-700 text-purple-800 font-bold ml-5 mt-5 py-2 px-4 border border-purple-700 rounded focus:outline-non" %>
  <% end %>
<% end %>